name: Incantations
main: me.bhsgoclub.incantations.Incantations
version: 1.4.2 beta release 
# (due to taking so long im starting with the minecraft build  its with)
Author: bhsgoclub, aka Michael Evatt
authors: drtshock
description: Spoken word magic. Adds true Incantations to your server.


